In [1]:
import numpy as np

In [14]:

# by using normal list if we do any operation it will just repeat the list

arr=[1,2,3,4,5]


print(arr*2)

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


### Array Dimension

In [19]:
# in Numpy we can eaily multiply each element directly


arr=np.array(arr)
print(arr*2)

print("Array dimention : ",arr.ndim)

[ 2  4  6  8 10]
Array dimention :  1


In [27]:
arr1=np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
print("Array dimention : ",arr1.ndim)

Array dimention :  2


In [18]:
arr2=np.array([[[1,2,3],
              [4,5,6],
              [7,8,9]],
              [[10,11,12],
               [13,14,15],
               [16,17,18]]])
print("Array dimention : ",arr2.ndim)

Array dimention :  3


### Accessing array elements

In [ ]:
# word=arr2[layer,row,column]

layer=int(input("Enter layer no:"))
row=int(input("Enter row no:"))
column=int(input("Enter column no:"))

print(arr2[layer,row,column])


5


In [28]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [30]:
print(arr1[0:2])

[[1 2 3]
 [4 5 6]]


In [33]:
print(arr1[0,2])

3


### Scalar arithmetic

In [34]:
print(arr+1)

[2 3 4 5 6]


In [36]:
print(arr-5)
print(arr*2)
print(arr**2)


[-4 -3 -2 -1  0]
[ 2  4  6  8 10]
[ 1  4  9 16 25]


### Random Numbers

In [ ]:
import numpy as np 

In [2]:
np.random.rand(5)

array([0.05395477, 0.24004437, 0.95728563, 0.93100194, 0.58805581])

In [3]:
np.random.rand(2,3)

array([[0.49345654, 0.45001696, 0.33631917],
       [0.64181712, 0.33720719, 0.66395501]])

In [12]:
# np.random.randint(start, stop, size)
np.random.seed(42)
np.random.randint(1, 10, 5)

array([7, 4, 8, 5, 7], dtype=int32)

In [13]:
colors = ["Red","Blue","Green"]

np.random.choice(colors)

np.str_('Blue')

In [14]:
import numpy as np

# 5 random decimals
print(np.random.rand(5))

# 10 random integers between 1 and 100
print(np.random.randint(1,101,10))

# Set seed
np.random.seed(42)
print(np.random.rand(3))

# Shuffle
arr = np.arange(1,11)
np.random.shuffle(arr)
print(arr)

[0.15599452 0.05808361 0.86617615 0.60111501 0.70807258]
[22 53  2 88 30 38  2 64 60 21]
[0.37454012 0.95071431 0.73199394]
[10  8  1  4  6  9  3  2  7  5]
